spring:
  ai:
    zhipuai:
      base_url:
      api_key:
      embedding:
        options:
          model: embedding-2
          dimensions: 1024
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
  datasource:
    url: jdbc:postgresql://172.16.1.87:32771/mysite
    username: postgres
    password: postgres
  application:
    name: spring-ai-qaadvisor
