spring:
  application:
    name: mcp-client
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
    openai:
      api_key: 
      chat:
        options:
          model: gpt-4o-mini