### Set the resource path for the file to be processed
### e.g., app.resource=file:///Users/yourname/Downloads/yourfile.pdf
###    or app.resource=classpath:/data/myfile.pdf
app:
  resource: file:E:/AI4Data/spring-ai-examples/spring-ai-rag-example/data/RDD_spark.pdf
spring:
  ai:
    zhipuai:
      base_url:
      api_key:
      embedding:
        options:
          model: embedding-2
          dimensions: 1024
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
    chat:
      observations:
        include-prompt: true
        include-completion: true
  datasource:
    url: jdbc:postgresql://172.16.1.87:32771/mysite
    username: postgres
    password: postgres
  application:
    name: spring-ai-rag-example
#  docker:
#    compose:
#      stop:
#        command: down
#        arguments: -v

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

  ### Set sampling probability to 1.0 to enable tracing
  ### on 100% of requests.
  tracing:
    sampling:
      probability: 1.0
